#!/bin/bash
#
# audlinks - create symbolic links to song files where possible to reduce
#    duplicate storage of audio. Link into my iTunes library.
#
# Written 01-Dec-2013 by Ronald Joe Record <rr at ronrecord dot com>
#
# Copyright (c) 2014, Ronald Joe Record
# All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# The Software is provided "as is", without warranty of any kind, express or
# implied, including but not limited to the warranties of merchantability,
# fitness for a particular purpose and noninfringement. In no event shall the
# authors or copyright holders be liable for any claim, damages or other
# liability, whether in an action of contract, tort or otherwise, arising from,
# out of or in connection with the Software or the use or other dealings in
# the Software.
#

I="/Volumes/Lacie_Porsche_1TB/iTunes/Music"
M="$HOME/Music"
W="/Volumes/My_Book_Studio/Audio/Imported"
USE_SUM=
TELL=

usage() {
    printf "\nUsage: audlinks [-M Music Dir] [-W Work Dir]"
    printf "\n\t[-I iTunes Dir] [-d] [-c] [-u]\n"
    printf "\nWhere:\n\t-d indicates tell me what you would do"
    printf "\n\t-c indicates use chksums"
    printf "\n\t-u displays this usage message\n"
    printf "\nDefaults are:\n\tMusic Dir = $M"
    printf "\n\tWork Dir = $W"
    printf "\n\tiTunes Dir = $I\n\n"
    exit 1
}

remlink() {
    printf "\nRemoving $2"
    [ "$TELL" ] || rm -f "$2"
    printf "\nLinking $1 to $2\n"
    [ "$TELL" ] || ln -s "$1" "$2"
}

FindAndLink() {
    find . -type f | while read i
    do
        found=
        if [ -L "$i" ]
        then
            continue
        else
            b=`basename "$i"`
            [ "$b" = "SUMS" ] && continue
            [ "$USE_SUM" ] && {
                ck1=`grep "$i" SUMS | awk ' { print $1 } '`
                [ "$ck1" ] || ck1=`cksum "$i" | awk ' { print $1 } '`
            }
            [ -f "$I/$b" ] && {
                found=1
                if [ "$USE_SUM" ]
                then
                    ck2 =`grep "$b" "$I/SUMS" | awk ' { print $1 } '`
                    [ "$ck2" ] || ck2=`cksum "$I/$b" | awk ' { print $1 } '`
                    [ $ck1 -eq $ck2 ] && {
                        remlink "$I/$b" "$i"
                    } 
                else
                    remlink "$I/$b" "$i"
                fi
            }
            [ $found ] || {
                [ "$TELL" ] && continue
                # Maybe the filename in iTunes has been changed. Search the SUMS
                [ "$USE_SUM" ] && {
                    iname=`grep $ck1 "$ISUMS"`
                    [ "$iname" ] && {
                        b=`echo $iname | awk ' { for(i=3;i<NF;i++) printf "%s",$i OFS; if (NF) printf "%s",$NF; printf ORS}'`
                        b=`echo $b | sed -e "s/\.\///"`
                        remlink "$I/$b" "$i"
                    }
                }
            }
        fi
    done
}

FindAndRemove() {
    find . -type l | while read i
    do
        ls -lL "$i" > /dev/null 2>&1
        [ $? -eq 0 ] || {
            printf "\nRemoving $i"
            [ "$TELL" ] || rm -f "$i"
        }
    done
}

while getopts M:W:I:dcu flag; do
    case $flag in
        M)
            M="$OPTARG"
            ;;
        W)
            W="$OPTARG"
            ;;
        I)
            I="$OPTARG"
            ;;
        d)
            TELL=1
            ;;
        c)
            USE_SUM=1
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

[ -d "$M" ] || {
    echo "$M does not exist or is not a directory. Exiting."
    exit 1
}
[ -d "$W" ] || {
    echo "$W does not exist or is not a directory. Exiting."
    exit 1
}
[ -d "$I" ] || {
    echo "$I does not exist or is not a directory. Exiting."
    exit 1
}

ISUMS="$I"/SUMS
# Not using this yet
WSUMS="$W"/SUMS
MSUMS="$M"/SUMS

# Update the iTunes SUMS file first
[ "$USE_SUM" ] && {
    cd "$I"
    printf "\nUpdating iTunes SUMS file ...\n"
    [ "$TELL" ] || updsums
}

# Link to file in iTunes library if it's a duplicate
if [ -d "$W" ]
then
    cd "$W"
    # Update the SUMS file if we are using cksums
    [ "$USE_SUM" ] && {
        printf "\nUpdating $W/SUMS\n"
        [ "$TELL" ] || updsums
    }
    printf "\nFinding and symlinking duplicate files in $W ...\n"
    FindAndLink
else
    echo "$W does not exist or is not a directory. Skipping."
fi
if [ -d "$M" ]
then
    cd "$M"
    # Update the SUMS file if we are using cksums
    [ "$USE_SUM" ] && {
        printf "\nUpdating $M/SUMS\n"
        [ "$TELL" ] || updsums
    }
    printf "\nFinding and symlinking duplicate files in $M ...\n"
    FindAndLink
else
    echo "$M does not exist or is not a directory. Skipping."
fi

# Remove broken links
if [ -d "$W" ]
then
    cd "$W"
    printf "\nRemoving broken links in $W ...\n"
    FindAndRemove
else
    echo "$W does not exist or is not a directory. Skipping."
fi
if [ -d "$M" ]
then
    cd "$M"
    printf "\nRemoving broken links in $M ...\n"
    FindAndRemove
else
    echo "$M does not exist or is not a directory. Skipping."
fi

echo "Done."
