#!/bin/bash
#
# chkinst - Check if installed versions of files in current directory are
#    different in order to determine if git repository is up-to-date.
#
# Written 8-Mar-2014 by Ronald Joe Record
#
# Note: this script assumes the files in your git repository are named the
#       same as their installed counterparts
# Copyright (c) 2014, Ronald Joe Record
# All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# The Software is provided "as is", without warranty of any kind, express or
# implied, including but not limited to the warranties of merchantability,
# fitness for a particular purpose and noninfringement. In no event shall the
# authors or copyright holders be liable for any claim, damages or other
# liability, whether in an action of contract, tort or otherwise, arising from,
# out of or in connection with the Software or the use or other dealings in
# the Software.
#

usage() {
    printf "\nUsage: chkinst [-u] [-a] [-d] [-f] [-i]"
    printf "\nWhere:"
    printf "\n\t-u displays this usage message"
    printf "\n\t-a indicates report on all files, not just those installed"
    printf "\n\t-d indicates display output of a diff between files"
    printf "\n\t-f indicates force update of installed file(s)"
    printf "\n\t-i indicates prompt for update of installed file(s)\n"
    exit 1
}

update() {
    printf "\nCopying $1 to $2\n"
    cp "$1" "$2"
}

differ() {
    echo "$1 differs from installed version $2"
    [ "$DIFF" ] && diff "$1" "$2"
    echo ""
    [ "$UPD" ] && {
        if [ "$FORCE" ]
        then
            update "$1" "$2"
        else
            while true
            do
                read -p "Do you want to install the new version ? (y/n) " yn
                case $yn in
                    [Yy]* ) update "$1" "$2"; break;;
                    [Nn]* ) break;;
                        * ) echo "Please answer yes or no.";;
                esac
            done
        fi
    }
}

check() {
    dnum=`diff "$1" "$2" | wc -l`
    [ $dnum -gt $3 ] && differ "$1" "$2"
}

ALL=
DIFF=
UPD=
FORCE=
while getopts adfiu flag; do
    case $flag in
        a)
            ALL=1
            ;;
        d)
            DIFF=1
            ;;
        i)
            UPD=1
            ;;
        f)
            UPD=1
            FORCE=1
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

for i in *
do
    [ -d "$i" ] && continue
    inst=`type -p "$i"`
    [ "$inst" ] || {
        [ "$ALL" ] && {
            echo "$i does not appear to be installed as a command. Skipping."
            echo ""
        }
        continue
    }
    # Special cases as the installed version may have configuration changes
    # The 3rd argument to the check() function is the number of lines the
    # installed script can differ before we report it differs.
    case "$i" in
        wb)
            check "$i" "$inst" 8
            ;;
        mkreadme|mkwmv)
            check "$i" "$inst" 12
            ;;
        *)
            cmp -s "$i" "$inst" || differ "$i" "$inst"
            ;;
    esac
done
