#!/bin/bash
#
# findempty - Find and report empty directories. Optionally, remove them.
#
# Written 12-May-2014 by Ronald Joe Record <rr at ronrecord dot com>
#

usage() {
    echo "Usage: findempty [-n] [-r] [-u] [directory1 directory2 ...]"
    echo ""
    echo "Where -r indicates remove empty directories."
    echo "      -n indicates tell me what you would do without doing it."
    echo "      -u displays this usage message and exits."
    echo "      directory1 directory2 ... is the list of directories to search"
    echo ""
    echo "Default is to list not remove and use the current working directory."
    echo ""
    exit 1
}

REMOVE=
TELL=
while getopts nru flag; do
    case $flag in
        n)
            TELL=1
            ;;
        r)
            REMOVE="Removing"
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

if [ $# -eq 0 ]
then
    DIRS="."
else
    DIRS="$@"
fi

for DIR in $DIRS
do
    [ -d "$DIR" ] || {
        echo "$DIR is not a directory or does not exist. Skipping."
        continue
    }
    [ "$TELL" ] && echo "Looking for empty directories in $DIR"
    find "$DIR" -type d | while read d
    do
        NUM=`ls -1a "$d" | grep -v .DS_Store | wc -l`
        [ $NUM -eq 2 ] && {
            echo $REMOVE $d
            [ "$REMOVE" ] && {
                if [ "$TELL" ]
                then
                    echo "rm -f $d/.DS_Store"
                    echo "rmdir $d"
                else
                    rm -f "$d"/.DS_Store
                    rmdir "$d"
                fi
            }
        }
    done 
done
