#!/bin/bash

PKG_NAME="DoctorFreeScripts"
PKG_DIR="Scripts"
PKG_VER="3.1"
SRC="${HOME}/src"
DEB="${SRC}/${PKG_DIR}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}.deb"

[ -f "${DEB}" ] || {
    echo "$DEB not found."
    for debs in ${SRC}/${PKG_DIR}/releases/*/${PKG_NAME}_*.deb
    do
      [ "${debs}" == "${SRC}/${PKG_DIR}/releases/*/${PKG_NAME}_*.deb" ] || {
        echo "Found existing packages:"
        echo "${debs}"
      }
    done
    echo "Exiting."
    exit 1
}

# Versions of apt prior to 1.1 do not support install by Debian filename
# You should probably be running a more recent version of apt
# On these early versions, install with the following:
#
# sudo dpkg -i "${DEB}"
# sudo apt-get install -f

sudo apt install "${DEB}"
