#!/bin/bash

PKG_NAME="DoctorFreeScripts"
SRC_DIR="DoctorFreeScripts"
SRC="${HOME}/src"

[ -f "${SRC}/${SRC_DIR}/VERSION" ] || {
  echo "Missing VERSION file: ${SRC}/${SRC_DIR}/VERSION"
  echo "Exiting"
  exit 1
}

. "${SRC}/${SRC_DIR}/VERSION"
PKG_VER=${VERSION}

DEB="${SRC}/${SRC_DIR}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}.deb"

[ -f "${DEB}" ] || {
    echo "$DEB not found."
    for debs in ${SRC}/${SRC_DIR}/releases/*/${PKG_NAME}_*.deb
    do
      [ "${debs}" == "${SRC}/${SRC_DIR}/releases/*/${PKG_NAME}_*.deb" ] || {
        echo "Found existing packages:"
        echo "${debs}"
      }
    done
    echo "Exiting."
    exit 1
}

# Versions of apt prior to 1.1 do not support install by Debian filename
# You should probably be running a more recent version of apt
# On these early versions, install with the following:
#
# sudo dpkg -i "${DEB}"
# sudo apt-get install -f

sudo apt install "${DEB}"
