#!/bin/bash
#
# Join 2 or 3 images then split the resulting composite in half
#

for dir in *
do
    [ -d "$dir" ] || continue
    [ -f "$dir"/Left.jpg ] || continue
    cd $dir
    MIDDLE=
    [ -f Middle.jpg ] && MIDDLE=Middle.jpg
    montage -border 0x0+0+0 -geometry 768x1024! Right.jpg $MIDDLE Left.jpg ../temp-$dir.jpg   
    convert -geometry 2048x768! ../temp-$dir.jpg ../temp3-$dir.jpg
    cd ..
    convert temp3-$dir.jpg -crop 50%x100% +repage comp3-$dir-%d.jpg
    mv comp3-$dir-0.jpg comp3-$dir-Left.jpg
    mv comp3-$dir-1.jpg comp3-$dir-Right.jpg
    rm temp3-$dir.jpg
    rm temp-$dir.jpg
done
