#!/bin/bash
#
# mvBackups - move Time Machine backups with bypass command
#
# A simple "mv ..." or even "sudo mv ..." wouldn't work on Time Machine
# backups as I got many many "operation not permitted". Use the bypass command.
#

OLD_BACKUP_DB="/Volumes/My_Book_Studio/Backups.backupdb"
NEW_BACKUP_DB="/Volumes/LaCie_8TB/Backups.backupdb"
BYPASS="/System/Library/Extensions/TMSafetyNet.kext/Contents/Helpers/bypass"
SHOWME=
SHOW_USAGE=
CMD=`basename $0`

usage() {
    printf "\nUsage: $CMD [-n] [-b path-to-bypass]\n"
    printf "\t[-s path-to-source-db] [-d path-to-destination-db] [-u]\n"
    printf "\nWhere:\n"
    printf "\t-n indicates no execution, just tell me what you would do\n"
    printf "\t-b path-to-bypass specifies the location of the bypass command\n"
    printf "\t-s path-to-source-db specifies the previous backup location\n"
    printf "\t-d path-to-destination-db specifies the new backup location\n"
    printf "\t-u prints this usage message and exits\n"
    printf "\nWith these arguments I would execute the following command:\n"
    printf "\nsudo ${BYPASS} mv ${OLD_BACKUP_DB} ${NEW_BACKUP_DB}\n\n"
    exit 1
}

while getopts b:d:s:nu flag; do
    case $flag in
        b)
            BYPASS="$OPTARG";
            ;;
        d)
            NEW_BACKUP_DB="$OPTARG";
            ;;
        s)
            OLD_BACKUP_DB="$OPTARG";
            ;;
        n)
            SHOWME=1;
            ;;
        u)
            SHOW_USAGE=1;
            ;;
    esac
done
shift $((OPTIND - 1));

# Check location of bypass command
[ -x "${BYPASS}" ] || {
    # Uh oh, maybe Apple moved it again. Try to locate bypass.
    POSSIBLE=`locate /bypass | grep -v xml | grep -v html`
    [ -x "${POSSIBLE}" ] || {
        printf "\n\n$BYPASS does not exist or is not executable.\nExiting.\n"
        usage
    }
    BYPASS="${POSSIBLE}"
}

# Check location of backup directory to move
[ -d "${OLD_BACKUP_DB}" ] || {
    printf "\n\n$OLD_BACKUP_DB does not exist or is not a directory."
    printf "\nExiting.\n"
    usage
}

# Check location of backup directory destination
[ -d "${NEW_BACKUP_DB}" ] && {
    printf "\n\n$NEW_BACKUP_DB already exists."
    printf "\nExiting.\n"
    usage
}

[ "${SHOW_USAGE}" ] && usage

printf "\nUsing ${BYPASS} to move Time Machine backups at:"
printf "\n\t${OLD_BACKUP_DB}\nto\n\t${NEW_BACKUP_DB}\n"

[ "$SHOWME" ] || {
    while true
    do
        read -p "Are you sure you want to proceed ? (y/n) " yn
        case $yn in
            [Yy]* ) break;;
            [Nn]* ) printf "\nExiting.\n"; usage;;
                * ) echo "Please answer yes or no.";;
        esac
    done
}

[ "$SHOWME" ] && {
    printf "\n\nWould execute the following command:\n"
    printf "\nsudo ${BYPASS} mv ${OLD_BACKUP_DB} ${NEW_BACKUP_DB}\n\n"
    exit 0
}

printf "\nMoving Time Machine backups at:"
printf "\n\t${OLD_BACKUP_DB}\nto\n\t${NEW_BACKUP_DB}\n"
printf "\nThis make take a while.\n"
sudo ${BYPASS} mv "${OLD_BACKUP_DB}" "${NEW_BACKUP_DB}"
