#!/bin/bash
#
# mvfem - Rename a downloaded Femjoy zip archive that contains two model
#         names to use only one model's name so it will work with femzip
#
# Written 9-Aug-2014 by Ronald Joe Record <rr at ronrecord dot com>
#
# Copyright (c) 2014, Ronald Joe Record
# All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# The Software is provided "as is", without warranty of any kind, express or
# implied, including but not limited to the warranties of merchantability,
# fitness for a particular purpose and noninfringement. In no event shall the
# authors or copyright holders be liable for any claim, damages or other
# liability, whether in an action of contract, tort or otherwise, arising from,
# out of or in connection with the Software or the use or other dealings in
# the Software.
#

D=$HOME/Downloads

usage() {
   printf "\nUsage: mvfem [-ridu] -m Model1 -p Model2"
   printf "\n\tRename Femjoy zip archive from:"
   printf "\n\t\tModel1_Model2_Photographer_Set_whatever.zip to"
   printf "\n\t\tModel1_Photographer_Set_whatever.zip"
   printf "\nWhere:"
   printf "\n\t-r reverses the roles of Model1 and Model2"
   printf "\n\t-i replaces %2e with ."
   printf "\n\t-d tells you what it would do"
   printf "\n\t-u displays this usage message"
   exit 1
}

DOT=
ECHO=
REVERSE=
while getopts m:p:rdiu flag; do
    case $flag in
        d)
            ECHO=1;
            ;;
        i)
            DOT=1;
            ;;
        r)
            REVERSE=1;
            ;;
        m)
            M="$OPTARG";
            ;;
        p)
            P="$OPTARG";
            ;;
        u)
            usage;
            ;;
        ?)
            usage;
            ;;
    esac
done

cd "$D"
for i in "$M"*"$P"_*.zip
do
    [ -f "$i" ] || {
        printf "$i is not a regular file. Skipping.\n"
        continue
    }
    if [ "$DOT" ]
    then
        T=`echo "$i" | sed -e "s/\%2e/\./g"`
        if [ "$ECHO" ]
        then
            echo "mv $i $T"
            echo ""
        else
            mv "$i" "$T"
        fi
    else
        if [ "$REVERSE" ]
        then
            T=`echo "$i" | sed -e "s/${M}, ${P}_/${P}_/"`
        else
            T=`echo "$i" | sed -e "s/${M}, ${P}_/${M}_/"`
        fi
        if [ "$ECHO" ]
        then
            printf "mv $i $T\n"
        else
            mv "$i" "$T"
        fi
    fi
done
