#!/bin/bash
#
# rmBackups - completely remove old unwanted Time Machine backups
#
# A simple "rm -rf ..." or even "sudo rm -rf ..." wouldn't work on Time Machine
# backups as I got many many "operation not permitted". I found this worked.
#

BACKUP_DB="/Volumes/My_Book_Studio/Backups.backupdb"
BYPASS="/System/Library/Extensions/TMSafetyNet.kext/Contents/Helpers/bypass"
SHOWME=
CMD=`basename $0`

usage() {
    printf "\nUsage: $CMD [-n] [-b path-to-bypass] [-d path-to-backupdb] [-u]\n"
    printf "\nWhere:\n"
    printf "\t-n indicates no execution, just tell me what you would do\n"
    printf "\t-b path-to-bypass specifies the location of the bypass command\n"
    printf "\t-d path-to-backupdb specifies the backup database location\n"
    printf "\t-u prints this usage message and exits\n\n"
    exit 1
}

while getopts b:d:nu flag; do
    case $flag in
        b)
            BYPASS="$OPTARG";
            ;;
        d)
            BACKUP_DB="$OPTARG";
            ;;
        n)
            SHOWME=1;
            ;;
        u)
            usage;
            ;;
    esac
done
shift $((OPTIND - 1));

# Check location of bypass command
[ -x "${BYPASS}" ] || {
    # Uh oh, maybe Apple moved it again. Try to locate bypass.
    POSSIBLE=`locate /bypass | grep -v xml | grep -v html`
    [ -x "${POSSIBLE}" ] || {
        printf "\n\n$BYPASS does not exist or is not executable.\nExiting.\n"
        usage
    }
    BYPASS="${POSSIBLE}"
}

# Check location of backup directory to remove
[ -d "${BACKUP_DB}" ] || {
    printf "\n\n$BACKUP_DB does not exist or is not a directory.\nExiting.\n"
    usage
}

printf "\nUsing ${BYPASS} to completely remove Time Machine backups at:"
printf "\n\t${BACKUP_DB}\n"

[ "$SHOWME" ] || {
    while true
    do
        read -p "Are you sure you want to proceed ? (y/n) " yn
        case $yn in
            [Yy]* ) break;;
            [Nn]* ) printf "\nExiting.\n"; usage;;
                * ) echo "Please answer yes or no.";;
        esac
    done
}

[ "$SHOWME" ] && {
    printf "\n\nWould execute the following command:\n"
    printf "\nsudo /System/Library/Extensions/TMSafetyNet.kext/Contents/Helpers/bypass rm -rf ${BACKUP_DB}\n\n"
    exit 0
}

printf "\nRemoving Time Machine backups at:"
printf "\n\t${BACKUP_DB}\n"
printf "\nThis make take a while.\n"
sudo /System/Library/Extensions/TMSafetyNet.kext/Contents/Helpers/bypass rm -rf "${BACKUP_DB}"
