#!/bin/bash
#
# updaplibs - sync my Aperture libraries to a USB flash drive
#    Note: to sync other directories use the -s, -a, and -t arguments
#          when invoked as updpicdir it syncs directories in my Pictures dir
#          when invoked as updmovdir it syncs directories in my Movies dir
#          when invoked as updhome it syncs directories in $HOME
#
# Written 10-Feb-2014 by Ronald Joe Record <rr@ronrecord.com>
#
# Copyright (c) 2014, Ronald Joe Record
# All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# The Software is provided "as is", without warranty of any kind, express or
# implied, including but not limited to the warranties of merchantability,
# fitness for a particular purpose and noninfringement. In no event shall the
# authors or copyright holders be liable for any claim, damages or other
# liability, whether in an action of contract, tort or otherwise, arising from,
# out of or in connection with the Software or the use or other dealings in
# the Software.
#

AP_LIBDIR="/Volumes/My_Book_Studio/Pictures/Libraries"
TRANSCEND="/Volumes/Transcend/Pictures/Aperture"
SUFFIX=".aplibrary"
NAME="updaplibs"
MYHOME=
TELL=
DRY=

usage() {
    printf "Usage: $NAME [-d] [-h] [-n] [-u] [-a source dir] [-t dest dir]\n"
    printf "                 [-s suffix] source-subdir [source-subdir2 ...]\n"
    printf "Where:\n\t-d indicates a dry run sync (no changes)\n"
    printf "\t-h indicates use directories from your HOME dir\n"
    printf "\t-n indicates tell me what you would do without doing it\n"
    printf "\t-u displays this usage message\n"
    printf "\t-a source dir sets the top-level source directory\n"
    printf "\t-t dest dir sets the top-level destination directory\n"
    printf "\t-s suffix sets the subdirectory suffix to look for\n"
    printf "\tsource-dir is the master directory hierarchy to sync from\n"
    printf "\tdest-dir is the directory hierarchy to be sync'd\n"
    printf "\nWhen invoked without arguments $NAME will attempt to sync\n"
    printf "all the directories in $TRANSCEND\n"
    printf "with corresponding directories in $AP_LIBDIR\n\n"
    exit 1
}

while getopts a:s:t:dhnu flag; do
    case $flag in
        d)
            DRY="n"
            ;;
        h)
            MYHOME=1
            ;;
        n)
            TELL=1
            ;;
        a)
            AP_LIBDIR="$OPTARG"
            ;;
        s)
            SUFFIX="$OPTARG"
            ;;
        t)
            TRANSCEND="$OPTARG"
            ;;
        u)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

NAME=`basename $0`
[ "$NAME" = "updpicdir" ] && {
    if [ "$MYHOME" ]
    then
        AP_LIBDIR="$HOME/Pictures"
    else
        AP_LIBDIR="/Volumes/My_Book_Studio/Pictures"
    fi
    TRANSCEND="/Volumes/Transcend/Pictures"
    SUFFIX=""
}
[ "$NAME" = "updmovdir" ] && {
    if [ "$MYHOME" ]
    then
        AP_LIBDIR="$HOME/Movies"
    else
        AP_LIBDIR="/Volumes/My_Book_Studio/Movies"
    fi
    TRANSCEND="/Volumes/Transcend/Movies"
    SUFFIX=""
}
[ "$NAME" = "updhome" ] && {
    AP_LIBDIR="$HOME"
    TRANSCEND="/Volumes/Transcend/Home"
    SUFFIX=""
}

[ -d "$TRANSCEND" ] || {
    echo "$TRANSCEND does not exist or is not a directory. Exiting."
    exit 1
}

cd "$TRANSCEND"

if [ $# -eq 0 ]
then
  for lib in *$SUFFIX
  do
    [ -d "$AP_LIBDIR/$lib" ] || {
        echo "$AP_LIBDIR/$lib does not exist or is not a directory. Skipping."
        continue
    }
    echo -n "Syncing $AP_LIBDIR/$lib to $TRANSCEND/$lib with rsync ... "
    DEL="--delete"
    [ -f "$TRANSCEND/$lib/.do_not_delete" ] && DEL=""
    if [ "$TELL" ]
    then
        echo ""
        echo "rsync -qa$DRY $DEL $AP_LIBDIR/$lib $TRANSCEND" 
    else
        if [ "$DRY" ]
        then
            rsync -van $DEL "$AP_LIBDIR/$lib" "$TRANSCEND" 
        else
            rsync -Wqa $DEL "$AP_LIBDIR/$lib" "$TRANSCEND" 
            touch "$TRANSCEND/.rsync_$lib"
        fi
    fi
    echo "done."
  done
else
    for libnam in $*
    do
      lib="$libnam$SUFFIX"
      [ -d "$AP_LIBDIR/$lib" ] || {
        echo "$AP_LIBDIR/$lib does not exist or is not a directory. Skipping."
        continue
      }
      echo -n "Syncing $AP_LIBDIR/$lib to $TRANSCEND/$lib with rsync ... "
      DEL="--delete"
      [ -f "$TRANSCEND/$lib/.do_not_delete" ] && DEL=""
      if [ "$TELL" ]
      then
          echo ""
          echo "rsync -qa$DRY $DEL $AP_LIBDIR/$lib $TRANSCEND" 
      else
          if [ "$DRY" ]
          then
              rsync -van $DEL "$AP_LIBDIR/$lib" "$TRANSCEND" 
          else
              rsync -Wqa $DEL "$AP_LIBDIR/$lib" "$TRANSCEND" 
              touch "$TRANSCEND/.rsync_$lib"
          fi
      fi
      echo "done."
    done
fi
