#!/bin/bash

LOCAL=/usr/local

for i in p*.sh bl*.sh
do
    j=`echo $i | sed -e "s/\.sh//"`
    diff $i ${LOCAL}/bin/$j > /dev/null || echo "$i differs from installed $j"
done

for i in *binance*.sh *bittrex*.sh
do
    j=`echo $i | sed -e "s/\.sh//"`
    diff $i ${HOME}/bin/$j > /dev/null || echo "$i differs from installed $j"
done
