#!/bin/bash

DOMAIN="https://pro-api.coinmarketcap.com"
CMCF="${HOME}/.coinmarketcap"

KEY=
[ -f ${CMCF} ] || {
    echo "Missing ${CMCF}. Place you Coinmarketcap API Key there and retry."
    exit 1
}
. ${CMCF}
[ "${KEY}" ] || {
    echo "Place you Coinmarketcap API Key in ${CMCF} and retry."
    exit 1
}

usejq=`type -p jq`
if [ "$usejq" ]
then
    curl -H "X-CMC_PRO_API_KEY: ${KEY}" \
         -H "Accept: application/json" \
         -d "start=1&limit=5000&convert=USD" \
         -G ${DOMAIN}/v1/cryptocurrency/listings/latest 2> /dev/null | jq '.'
else
    curl -H "X-CMC_PRO_API_KEY: ${KEY}" \
         -H "Accept: application/json" \
         -d "start=1&limit=5000&convert=USD" \
         -G ${DOMAIN}/v1/cryptocurrency/listings/latest 2> /dev/null
fi


