#!/bin/bash

DOMAIN="https://api.binance.com"
ENDPT="api/v3/order"
PAIR="ETHBTC"
BINF="${HOME}/.binance"

usage() {
    printf "\nUsage: BinanceOrder [-a] [-b|-s] [-P pair] [-p price] [-q quantity] [-t type]"
    printf "\n\t[-f timeInForce] [-r recvWindow] [-d price_percent_offset]"
    printf "\n\t[-n] [-v] [-u]"
    printf "\n\nWhere:"
    printf "\n\t-a indicates use the retrieved average price of the specified pair"
    printf "\n\t-b indicates BUY"
    printf "\n\t-s indicates SELL"
    printf "\n\t\tOne of -b or -s must be specified, there is no default"
    printf "\n\tpair specifies a trading pair in the format ETHBTC (the default pair)"
    printf "\n\tprice specifies the price per coin/token"
    printf "\n\tquantity specifies the number of tokens/coins to buy"
    printf "\n\ttype specifies the type of trade. Valid type values are:"
    printf "\n\t\tLIMIT MARKET STOP_LOSS STOP_LOSS_LIMIT"
    printf "\n\t\tTAKE_PROFIT TAKE_PROFIT_LIMIT LIMIT_MAKER"
    printf "\n\t\tTrade type defaults to LIMIT"
    printf "\n\ttimeInForce specifies the length of time the order will stay in force."
    printf "\n\tValid timeInForce values are:"
    printf "\n\t\tGTC IOC FOK"
    printf "\n\t\ttimeInForce defaults to GTC"
    printf "\n\trecvWindow specifies the time in milliseconds the API request is valid"
    printf "\n\tprice_percent_offset indicates calculate the price based on the"
    printf "\n\t\taverage or specified price, buying at lower value and selling at higher"
    printf "\n\t-n indicates to tell me what you would do but do nothing"
    printf "\n\t-v indicates to verify the specified trade before sending the request."
    printf "\n\t\tIf indicated, you will be prompted to approve the trade before it is sent"
    printf "\n\t-u indicates display this usage message\n"
}

side_offset() {
    if [ "${SIDE}" == "BUY" ]
    then
        percent=`echo "scale=10; (100 - ${OFFSET}) / 100" | bc`
    else
        percent=`echo "scale=10; (100 + ${OFFSET}) / 100" | bc`
    fi
    PRICE=`echo "scale=50; $1 * ${percent}" | bc`
    echo "Revised price from $1 to ${PRICE}"
}

display_trade() {
    echo ""
    echo "The following curl command would be used to submit your order"
    echo ""
    printf "%s" "curl -H X-MBX-APIKEY: <trading key> "
    echo -n "-X POST -H Accept: application/json "
    echo -n "-G ${DOMAIN}/${ENDPT}?"
    echo -n "symbol=${PAIR}&side=${SIDE}&type=${TYPE}&"
    echo -n "timeInForce=${TINF}&quantity=${QUANTITY}&price=${PRICE}&"
    echo -n "recvWindow=${RECV}&timestamp=${TIM}&signature=${SIG}"
    echo ""
    echo ""
}

# Get the Binance trading key and secret
KEY=
SEC=
[ -f ${BINF} ] || {
    echo "Missing ${BINF}. Place you Binance API Key and Secret there and retry."
    exit 1
}
. ${BINF}
[ "${KEY}" ] || {
    echo "Place you Binance API Key and Secret in ${BINF} and retry."
    exit 1
}
[ "${SEC}" ] || {
    echo "Place you Binance API Key and Secret in ${BINF} and retry."
    exit 1
}

# Process the command line arguments
useavg=
tellme=
dispus=
verify=
OFFSET=
PRICE=
SIDE=
TYPE="LIMIT"
TINF="GTC"
RECV=5000
while getopts absd:f:P:p:q:r:t:nuv flag; do
    case $flag in
        a)
            useavg=1
            ;;
        b)
            SIDE="BUY"
            ;;
        s)
            SIDE="SELL"
            ;;
        d)
            OFFSET=$OPTARG
            ;;
        f)
            TINF=$OPTARG
            ;;
        p)
            PRICE=$OPTARG
            ;;
        q)
            QUANTITY=$OPTARG
            ;;
        r)
            RECV=$OPTARG
            ;;
        P)
            PAIR=$OPTARG
            ;;
        t)
            TYPE=$OPTARG
            ;;
        n)
            tellme=1
            ;;
        u)
            dispus=1
            ;;
        v)
            verify=1
            ;;
    esac
done
shift $(( OPTIND - 1 ))

[ "$SIDE" ] || {
    usage
    echo "Trade side must be specified with either -b (BUY) or -s (SELL). Exiting."
    exit 1
}

[ "$PRICE" ] && {
    [ "$useavg" ] && {
        usage
        echo "Incompatible arguments <-a> and <-p price>. Use only one or neither."
        echo "You can specify the price with -p or use the average price with -a. Exiting."
        exit 1
    }
}

[ "$PRICE" ] || {
    if [ "$useavg" ]
    then
        PRICE=`curl -X GET -H "Accept: */*" \
             "${DOMAIN}/api/v3/avgPrice?symbol=${PAIR}" 2> /dev/null | \
             jq '.price' | sed -e "s/\"//g"`
        echo "Using retrieved average price of ${PRICE} for ${PAIR} as base price"
    else
        echo "Price not specified with <-a> or <-p value>"
        PRICE=`curl -X GET -H "Accept: */*" \
             "${DOMAIN}/api/v1/ticker/price?symbol=${PAIR}" 2> /dev/null | \
             jq '.price' | sed -e "s/\"//g"`
        echo "Set price to current ticker for ${PAIR}: ${PRICE}"
    fi
}

[ "$dispus" ] && {
    usage
    [ "$tellme" ] || exit 1
}

[ "$OFFSET" ] && {
    echo "Calculating price from specified price of ${PRICE} and offset of ${OFFSET}%"
    side_offset "$PRICE"
}

TIM=$(date +%s)
SIG=`echo -n "symbol=${PAIR}&side=${SIDE}&type=${TYPE}&timeInForce=${TINF}&quantity=${QUANTITY}&price=${PRICE}&recvWindow=${RECV}&timestamp=${TIM}" | openssl dgst -sha256 -hmac "${SEC}"`

[ "$tellme" ] && {
    display_trade
    exit 0
}

[ "$verify" ] && {
    display_trade
    while true
    do
        read -p "Do you want to submit this order ? (y/n) " yn
        case $yn in
            [Yy]* ) break;;
            [Nn]* ) printf "\nExiting.\n"; exit 1;;
                * ) echo "Please answer yes or no.";;
        esac
    done
}

usejq=`type -p jq`
if [ "$usejq" ]
then
    curl -H "X-MBX-APIKEY: ${KEY}" -X POST \
         -H "Accept: application/json" \
         -d "symbol=${PAIR}&side=${SIDE}&type=${TYPE}" \
         -d "timeInForce=${TINF}&quantity=${QUANTITY}&price=${PRICE}" \
         -d "recvWindow=${RECV}&timestamp=${TIM}&signature=${SIG}" \
         -G ${DOMAIN}/${ENDPT} 2> /dev/null | jq '.'
else
    curl -H "X-MBX-APIKEY: ${KEY}" -X POST \
         -H "Accept: application/json" \
         -d "symbol=${PAIR}&side=${SIDE}&type=${TYPE}" \
         -d "timeInForce=${TINF}&quantity=${QUANTITY}&price=${PRICE}" \
         -d "recvWindow=${RECV}&timestamp=${TIM}&signature=${SIG}" \
         -G ${DOMAIN}/${ENDPT} 2> /dev/null
fi
