#!/bin/bash

DOMAIN="https://api.binance.com"
ENDPT="api/v3/order"
PAIR="BTCETH"
BINF="${HOME}/.binance"

usage() {
    printf "\nUsage: limitbuy [-s pair] [-p price] [-q quantity] [-n] [-u]"
    printf "\nWhere:"
    printf "\n\tpair specifies a trading pair in the format BTCETH"
    printf "\n\tprice specifies the limit price per coin/token"
    printf "\n\tquantity specifies the number of tokens/coins to buy"
    printf "\n\t-n indicates to tell me what you would do but do nothing"
    printf "\n\t-u indicates display this usage message\n"
}

# Get the Binance trading key and secret
KEY=
SEC=
[ -f ${BINF} ] || {
    echo "Missing ${BINF}. Place you Binance API Key and Secret there and retry."
    exit 1
}
. ${BINF}
[ "${KEY}" ] || {
    echo "Place you Binance API Key and Secret in ${BINF} and retry."
    exit 1
}
[ "${SEC}" ] || {
    echo "Place you Binance API Key and Secret in ${BINF} and retry."
    exit 1
}

# Process the command line arguments
tellme=
dispus=
while getopts s:p:q:nu flag; do
    case $flag in
        p)
            PRICE=$OPTARG
            ;;
        q)
            QUANTITY=$OPTARG
            ;;
        s)
            PAIR=$OPTARG
            ;;
        n)
            tellme=1
            ;;
        u)
            dispus=1
            ;;
    esac
done
shift $(( OPTIND - 1 ))

[ "$dispus" ] && {
    usage
    [ "$tellme" ] || exit 1
}

TIM=$(date +%s)
SIG=`echo -n "symbol=${PAIR}&side=BUY&type=LIMIT&timeInForce=GTC&quantity=${QUANTITY}&price=${PRICE}&recvWindow=5000&timestamp=${TIM}" | openssl dgst -sha256 -hmac "${SEC}"`

[ "$tellme" ] && {
    echo ""
    printf "%s" "curl -H X-MBX-APIKEY: <trading key> "
    echo -n "-X POST -H Accept: application/json "
    echo -n "-G ${DOMAIN}/${ENDPT}?"
    echo -n "symbol=${PAIR}&side=BUY&type=LIMIT&"
    echo -n "timeInForce=GTC&quantity=${QUANTITY}&price=${PRICE}&"
    echo -n "recvWindow=5000&timestamp=${TIM}&signature=${SIG}"
    echo ""
    exit 0
}

usejq=`type -p jq`
if [ "$usejq" ]
then
    curl -H "X-MBX-APIKEY: ${KEY}" -X POST \
         -H "Accept: application/json" \
         -d "symbol=${PAIR}&side=BUY&type=LIMIT" \
         -d "timeInForce=GTC&quantity=${QUANTITY}&price=${PRICE}" \
         -d "recvWindow=5000&timestamp=${TIM}&signature=${SIG}" \
         -G ${DOMAIN}/${ENDPT} 2> /dev/null | jq '.'
else
    curl -H "X-MBX-APIKEY: ${KEY}" -X POST \
         -H "Accept: application/json" \
         -d "symbol=${PAIR}&side=BUY&type=LIMIT" \
         -d "timeInForce=GTC&quantity=${QUANTITY}&price=${PRICE}" \
         -d "recvWindow=5000&timestamp=${TIM}&signature=${SIG}" \
         -G ${DOMAIN}/${ENDPT} 2> /dev/null
fi
