#!/bin/bash

PID=`ps -ef|grep /usr/local/bin/ethminer|grep -v grep|awk ' { print $2 } '`
NUM=`echo $PID | wc -w`
TELL=1

[ "$1" == "-q" ] && TELL=

if [ $NUM -gt 0 ]
then
    [ "$TELL" ] && echo "ethminer is running"
    if [ -f ${HOME}/.miner_enabled ]
    then
        [ "$TELL" ] && echo "ethminer is enabled"
        exit 0
    else
        exit $NUM
    fi
else
    [ "$TELL" ] && echo "ethminer is not running"
    if [ -f ${HOME}/.miner_disabled ]
    then
        [ "$TELL" ] && echo "ethminer is disabled"
        exit 1
    else
        exit 0
    fi
fi
