#!/bin/bash

# Exit if miner not running or miner enabled
[ -x /usr/local/bin/check_miner ] && {
    /usr/local/bin/check_miner -q
    [ $? -gt 0 ] || {
        exit 1
    }
}

PID=`ps -ef|grep /usr/local/bin/ethminer|grep -v grep|awk ' { print $2 } '`
sudo kill -9 $PID
