#!/bin/bash
#
# timemachinedelete - remove specified Time Machine backups
#
# Usage: timemachinedelete [-n] [-u] <date> <date> [oldest]
#     Where -n indicates tell me what you would do but don't do it
#           -u displays a usage message
#           <date> indicates a date in the format YYYY-MM-DD-HHMMSS
#           [oldest] will select the oldest backup to delete
#

BACKUPDB="/Volumes/Seagate_BPH_8TB/Backups.backupdb/Ronnies-Mac-Pro"
TELLME=

usage() {
    printf "\nUsage: timemachinedelete [-n] [-u] <date> <date> [oldest]"
    printf "\n\tWhere"
    printf "\n\t-n indicates tell me what you would do but don't do it"
    printf "\n\t-u displays a usage message"
    printf "\n\t<date> indicates a date in the format YYYY-MM-DD-HHMMSS"
    printf "\n\t[oldest] will select the oldest backup to delete\n"
    exit 1
}

[ "$1" == "-n" ] && {
    TELLME=1
    shift
}
[ "$1" == "-u" ] && {
    usage
}

if [ $# -eq 0 ]
then
    DATES="oldest"
else
    DATES="$*"
fi

for date in $DATES
do
    [ "$date" == "oldest" ] && {
        date=`ls -1t "$BACKUPDB" | tail -1`
    }
    [ -d "$BACKUPDB/$date" ] || {
        echo "$BACKUPDB/$date does not exist or is not a directory. Skipping."
        continue
    }
    if [ "$TELLME" ]
    then
        echo "sudo tmutil delete $BACKUPDB/$date"
    else
        sudo tmutil delete "$BACKUPDB/$date"
    fi
done
