#!/bin/bash

for site in *
do
  [ -d $site/.git ] && {
    cd $site
    if [[ `git status --porcelain` ]]; then
      updgit -a -m "Auto-generate sitemap with jekyll-sitemap plugin"
    fi
    cd ..
  }
done
