#!/bin/bash

PAGES="archive.ronrecord.com \
       asciigames.neoman.dev \
       asciiville.dev \
       ide.lazyman.dev \
       lazyman.dev \
       mirrorcommand.dev \
       musicplayerplus.dev \
       neoman.dev \
       rooncommand.dev \
       skunkware.dev \
       webdev.lazyman.dev"

for site in ${PAGES}
do
  if [ -d ${site}/.git ]
  then
    cd ${site}
    git pull
    cd ..
  else
    [ -d ${site} ] && mv ${site} ${site}$$
    gh repo clone doctorfree/${site}
  fi
done
