#!/bin/bash

#PAGES="archive.ronrecord.com \
#       asciigames.neoman.dev \
#       asciiville.dev \
#       ide.lazyman.dev \
#       lazyman.dev \
#       mirrorcommand.dev \
#       musicplayerplus.dev \
#       neoman.dev \
#       rooncommand.dev \
#       skunkware.dev \
#       webdev.lazyman.dev"
#
#for site in ${PAGES}

for site in *
do
  [ -d ${site}/.git ] && {
    cd ${site}
    git pull
    cd ..
  }
done
