#!/bin/bash
#
## @file Wallpapers/diffem.sh
## @brief Diff current git repo versions against installed versions
## @author Ronald Joe Record (rr at ronrecord dot com)
## @copyright Copyright (c) 2016, Ronald Joe Record, all rights reserved.
## @date Written 24-Sep-2016
## @version 1.0.1
##

WDIR="/Volumes/My_Book_Studio/Pictures/Work/Wallhaven"

diffit() {
    f="$1"
    if [ -f "$f" ]
    then
        j=`echo $1 | sed -e "s/\.sh//"`
        if [ -f $WDIR/$j ]
        then
            echo "Creating /tmp/$j.diff"
            diff $1 $WDIR/$j > /tmp/$j.diff
        else
            if [ -f /usr/local/bin/$j ]
            then
                echo "Creating /tmp/$j.diff"
                diff $1 /usr/local/bin/$j > /tmp/$j.diff
            else
                echo "$WDIR/$j does not exist or is not a plain file. Skipping."
            fi
        fi
    else
        echo "$f does not exist or is not a plain file. Skipping."
    fi
}

if [ "$1" ]
then
    for i in $*
    do
        diffit "$i"
    done
else
    for i in *.sh utils
    do
        diffit "$i"
    done
fi
