#!/bin/bash
#
## @file Wallpapers/diffem.sh
## @brief Diff current git repo versions against installed versions
## @author Ronald Joe Record (rr at ronrecord dot com)
## @copyright Copyright (c) 2016, Ronald Joe Record, all rights reserved.
## @date Written 24-Sep-2016
## @version 1.0.1
##

WDIR="/Volumes/My_Book_Studio/Pictures/Work/Wallhaven"

create_diff() {
    if [ "$1" = "wb.sh" ] || [ "$1" = "wh.sh" ]
    then
        dnum=`diff "$1" "$2" | wc -l`
        [ $dnum -ne 8 ] && {
            echo "Creating /tmp/$3.diff"
            diff $1 $2 > /tmp/$3.diff
        }
    else
        cmp -s $1 $2 || {
            echo "Creating /tmp/$3.diff"
            diff $1 $2 > /tmp/$3.diff
        }
    fi
}

diffit() {
    f="$1"
    if [ -f "$f" ]
    then
        j=`echo $1 | sed -e "s/\.sh//"`
        if [ -f $WDIR/$j ]
        then
            create_diff $f $WDIR/$j $j
        else
            if [ -f /usr/local/bin/$j ]
            then
                create_diff $f /usr/local/bin/$j $j
            else
                echo "$WDIR/$j does not exist or is not a plain file. Skipping."
            fi
        fi
    else
        echo "$f does not exist or is not a plain file. Skipping."
    fi
}

rm -f /tmp/*.diff
if [ "$1" ]
then
    for i in $*
    do
        diffit "$i"
    done
else
    for i in *.sh utils
    do
        [ "$i" = "wallhaven.sh" ] && continue
        diffit "$i"
    done
fi

H=`pwd`
cd "$WDIR"
ONLY=
for i in c* f* g* m* u*
do
    j="$i".sh
    [ -f "$H"/"$i" ] && continue
    [ -f "$H"/"$j" ] && continue
    ONLY="$i $ONLY"
done
[ "$ONLY" ] && {
    echo ""
    echo "Only in $WDIR :"
    for i in $ONLY
    do
        printf "\n\t$i"
    done
    printf "\n"
}
