#!/bin/bash

DDIR="/Volumes/My_Book_Studio/Pictures/Work/Wallhaven/Anime"

query=
numdown=480
categories=010
filters=001

while getopts n:c:f:q: flag; do
    case $flag in
        n)
            numdown=$OPTARG
            ;;
        c)
            categories=$OPTARG
            ;;
        f)
            filters=$OPTARG
            ;;
        q)
            query="$OPTARG"
    esac
done
shift $(( OPTIND - 1 ))

[ -d "${DDIR}" ] || mkdir -p "${DDIR}"
cd "${DDIR}"
page=1
pics=`echo *.jpg`
numpics=0
pngs=`echo *.png`
numpngs=0
[ "$pics" = "*.jpg" ] || {
    numpics=`ls -1 *.jpg | wc -l`
}
[ "$pngs" = "*.png" ] || {
    numpngs=`ls -1 *.png | wc -l`
}
totpics=`expr $numpics + $numpngs`
numpage=`expr $totpics / 24`
page=`expr $numpage + 1`

wh -l "${DDIR}" \
   -n $numdown \
   -s $page \
   -c $categories \
   -f $filters \
   -t standard \
   -p 0

