#!/bin/bash

DDIR="/Volumes/My_Book_Studio/Pictures/Work/Wallhaven/Anime"

[ -d "${DDIR}" ] || mkdir -p "${DDIR}"
cd "${DDIR}"
page=1
pics=`echo *.jpg`
[ "$pics" = "*.jpg" ] || {
    numpics=`ls -1 *.jpg | wc -l`
    numpage=`expr $numpics / 24`
    page=`expr $numpage + 1`
}

wh -l "${DDIR}" \
   -n 480 \
   -s $page \
   -t standard \
   -p 0

