#!/bin/bash

# Set this to your top-level Wallhaven download directory path
WHDIR="/Volumes/My_Book_Studio/Pictures/Work/Wallhaven"

query=
numdown=480
page=
categories=111
filters=001

usage() {
    printf "\nUsage: get-search [-n num] [-c cat] [-f filter] [-p page]"
    printf " [-q search] [-u]"
    printf "\n\nWhere:\n\t-n num specifies the number of downloads"
    printf "\n\t-c cat specifies the category mask (001 - 111)"
    printf "\n\t-f filter specifies the filter mask (001 - 111)"
    printf "\n\t-p page specifies the start page"
    printf "\n\t-q search specifies the search terms ( + for AND, space for OR)"
    printf "\n\t-u displays this usage message\n"
    exit 1
}

while getopts n:c:f:p:q:u flag; do
    case $flag in
        n)
            numdown=$OPTARG
            ;;
        c)
            categories=$OPTARG
            ;;
        f)
            filters=$OPTARG
            ;;
        p)
            page=$OPTARG
            ;;
        q)
            query="$OPTARG"
            ;;
        *)
            usage
            ;;
    esac
done
shift $(( OPTIND - 1 ))

[ "$query" ] || query="$*"

# Replace spaces and plusses in search terms with underscores to construct
# the subdirectory name to use
QDIR=`echo ${query} | sed -e "s/ /_/g" -e "s/+/_/g"`
DDIR="${WHDIR}/${QDIR}"

[ -d "${DDIR}" ] || mkdir -p "${DDIR}"
cd "${DDIR}"

# Try to set a reasonable start page if one has not been specified
[ "$page" ] || {
    pics=`echo *.jpg`
    numpics=0
    pngs=`echo *.png`
    numpngs=0
    [ "$pics" = "*.jpg" ] || {
        numpics=`ls -1 *.jpg | wc -l`
    }
    [ "$pngs" = "*.png" ] || {
        numpngs=`ls -1 *.png | wc -l`
    }
    totpics=`expr $numpics + $numpngs`
    numpage=`expr $totpics / 24`
    page=`expr $numpage + 1`
}

wh -l "${DDIR}" -n $numdown -s $page -t search \
   -c $categories -f $filters -q "${query}" -p 0

cd "${WHDIR}"
./findups "${QDIR}"
