#!/bin/bash

query=
numdown=480
page=
categories=111
filters=001

while getopts n:c:f:p:q: flag; do
    case $flag in
        n)
            numdown=$OPTARG
            ;;
        c)
            categories=$OPTARG
            ;;
        f)
            filters=$OPTARG
            ;;
        p)
            page=$OPTARG
            ;;
        q)
            query="$OPTARG"
    esac
done
shift $(( OPTIND - 1 ))

[ "$query" ] || query="$*"
QDIR=`echo ${query} | sed -e "s/ /_/g" -e "s/+/_/g"`
DDIR="/Volumes/My_Book_Studio/Pictures/Work/Wallhaven/${QDIR}"

[ -d "${DDIR}" ] || mkdir -p "${DDIR}"
cd "${DDIR}"
[ "$page" ] || {
    pics=`echo *.jpg`
    numpics=0
    pngs=`echo *.png`
    numpngs=0
    [ "$pics" = "*.jpg" ] || {
        numpics=`ls -1 *.jpg | wc -l`
    }
    [ "$pngs" = "*.png" ] || {
        numpngs=`ls -1 *.png | wc -l`
    }
    totpics=`expr $numpics + $numpngs`
    numpage=`expr $totpics / 24`
    page=`expr $numpage + 1`
}

wh -l "${DDIR}" -n $numdown -s $page -t search \
                -c $categories -f $filters -q "${query}" -p 0

