#!/bin/bash
# postinst script for doctorfree-scripts
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
        export PATH=/usr/local/bin:$PATH
        # Scripts for which links will be made in /usr/local/bin
        EXPORTS="any2any aptsearch audlinks backgrounds build-sgminer cap2any \
                 catinfo check_ethminer chk chkall chkrel ckdown ckdups clndl \
                 convm4a counts cpBackups cptoflash create_speech createswapfile \
                 cron.bash dltor dtox ethos2local favrotate fdups fempiclinks \
                 femzip filenuminc filenumset findabslinks findbroken findempty \
                 findgrep findups findupthumbs fixabslinks fixlinks get-all \
                 get-anime get-artists get-background getcounts get-favorites \
                 get-general getgittag gethue get-label get-latest get-list \
                 get-missing get-model get-model-latest get-models get-number \
                 get-people get-photographers getpyethereum getsaver get-search \
                 get-sizes gettagdate get-top gitarch gitbranch gitdiff githubgit \
                 githubinit gitinit gitlog gitlogtoday gitshow gittag hangup \
                 imfonts.pl installamdgpu install-to-project-repo.py instdeb \
                 keybinds-pipemenu killscreen latest lgitinit linkhaven listgit \
                 mandelhist mkcomps mkdiffs"
        DFS="/usr/local/DoctorFreeScripts"
        ANY="ape2m4a ape2mp4 avi2mp4 f4v2mp4 flv2mp4 \
             m4a2mp3 m4v2mp4 mkv2mp4 mov2mp4 mp42m4v \
             mpg2mp4 png2jpg wma2m4a wmv2m4v wmv2mp4"
        CAP="cap2m4v cap2mp4"
        CHK="chkaplibs chkitunes chkpicdir chkmovdir chkauddir chkhome"
        [ -d /usr/local ] || mkdir /usr/local
        [ -d /usr/local/bin ] || mkdir /usr/local/bin
        cd /usr/local/bin
        for command in ${EXPORTS}
        do
            [ -f ${DFS}/bin/${command} ] && {
                if [ -f ${command} ]
                then
                    diff ${DFS}/bin/${command} ${command} > /dev/null && {
                        rm -f ${command}
                        ln -s ${DFS}/bin/${command} .
                    }
                else
                    ln -s ${DFS}/bin/${command} .
                fi
            }
        done
        any2any=${DFS}/bin/any2any
        for any in ${ANY}
        do
            if [ -f ${any} ]
            then
                diff ${any} ${any2any} > /dev/null && {
                    rm -f ${any}
                    ln -s ${any2any} ${any}
                }
            else
                ln -s ${any2any} ${any}
            fi
        done
        cap2any=${DFS}/bin/cap2any
        for cap in ${CAP}
        do
            if [ -f ${cap} ]
            then
                diff ${cap} ${cap2any} > /dev/null && {
                    rm -f ${cap}
                    ln -s ${cap2any} ${cap}
                }
            else
                ln -s ${cap2any} ${cap}
            fi
        done
        chk=${DFS}/bin/chk
        for lnk in ${CHK}
        do
            if [ -f ${lnk} ]
            then
                diff ${lnk} ${chk} > /dev/null && {
                    rm -f ${lnk}
                    ln -s ${chk} ${lnk}
                }
            else
                ln -s ${chk} ${lnk}
            fi
        done
        [ -d /usr/local/share ] || mkdir /usr/local/share
        [ -d /usr/local/share/bash ] || mkdir /usr/local/share/bash
        cd /usr/local/share/bash
        for script in ${DFS}/share/bash/*
        do
            [ "${script}" ==  "${DFS}/share/bash/*" ] && continue
            b=`basename ${script}`
            if [ -f $b ]
            then
                diff $b ${script} > /dev/null && {
                    rm -f $b
                    ln -s ${script} .
                }
            else
                ln -s ${script} .
            fi
        done
        [ -d /usr/local/share/images ] || mkdir /usr/local/share/images
        cd /usr/local/share/images
        for image in ${DFS}/share/images/*
        do
            [ "${image}" ==  "${DFS}/share/images/*" ] && continue
            b=`basename ${image}`
            if [ -f $b ]
            then
                diff $b ${image} > /dev/null && {
                    rm -f $b
                    ln -s ${image} .
                }
            else
                ln -s ${image} .
            fi
        done
        [ -x ${DFS}/bin/dl_fred_scripts ] && ${DFS}/bin/dl_fred_scripts
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
