#!/bin/bash
# postinst script for doctorfree-scripts
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
        export DFS="/usr/local/DoctorFreeScripts"
        [ -d /usr/local ] || mkdir /usr/local
        [ -d /usr/local/bin ] || mkdir /usr/local/bin
        cd /usr/local/bin
        for command in ${DFS}/bin/*
        do
            [ "${command}" ==  "${DFS}/bin/*" ] && continue
            b=`basename ${command}`
            if [ -f $b ]
            then
                diff $b ${command} > /dev/null && {
                    rm -f $b
                    ln -s ${command} .
                }
            else
                ln -s ${command} .
            fi
        done
        [ -d /usr/local/share ] || mkdir /usr/local/share
        [ -d /usr/local/share/bash ] || mkdir /usr/local/share/bash
        cd /usr/local/share/bash
        for script in ${DFS}/share/bash/*
        do
            [ "${script}" ==  "${DFS}/share/bash/*" ] && continue
            b=`basename ${script}`
            if [ -f $b ]
            then
                diff $b ${script} > /dev/null && {
                    rm -f $b
                    ln -s ${script} .
                }
            else
                ln -s ${script} .
            fi
        done
        [ -d /usr/local/share/images ] || mkdir /usr/local/share/images
        cd /usr/local/share/images
        for image in ${DFS}/share/images/*
        do
            [ "${image}" ==  "${DFS}/share/images/*" ] && continue
            b=`basename ${image}`
            if [ -f $b ]
            then
                diff $b ${image} > /dev/null && {
                    rm -f $b
                    ln -s ${image} .
                }
            else
                ln -s ${image} .
            fi
        done
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
