#!/bin/bash
# prerm script for doctorfree-scripts
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    remove|upgrade|deconfigure)
        [ -d /usr/local/bin ] && {
            cd /usr/local/bin
            for command in /usr/local/DoctorFreeScripts/bin/*
            do
                b=`basename ${command}`
                [ -L $b ] && {
                    readlink $b | grep /usr/local/DoctorFreeScripts > /dev/null && rm -f $b
                }
            done
        }
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
